base_lr: 0.0005
batch_size: 256
bps_size: 4096
c_weights_path: cgrasp/configs/rhand_weight.npy
cgrasp_model_path: cgrasp/pretrained/cgrasp.pt
cuda_id: 0
dataset_dir: ../../GRAB/data/
expr_ID: V00
kl_coef: 0.005
latentD: 16
log: true
log_every_epoch: 2
n_epochs: 500
n_neurons: 512
n_workers: 10
no_TR_enc: true
reg_coef: 0.0005
rhm_path: ../../models/mano
seed: 4815
try_num: 75
vpe_path: cgrasp/configs/verts_per_edge.npy
